dist: xenial
sudo: required
language:
  - cpp
compiler:
  - gcc
env:
    global:
    - LLVM_VERSION=8.0.0
    - CMAKE_VERSION=3.15.2
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
script:
    - echo "DEPS_DIR=${DEPS_DIR}"
    - echo "LLVM_DIR=${LLVM_DIR}"
    - echo "Downloading Ninja ..."
    - mkdir -p ${DEPS_DIR}/ninja
    - NINJA_URL=https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
    - travis_retry wget --no-check-certificate --quiet -O ${DEPS_DIR}/ninja/ninja.zip ${NINJA_URL}
    - unzip ${DEPS_DIR}/ninja/ninja.zip -d ${DEPS_DIR}/ninja
    - export PATH=${DEPS_DIR}/ninja:${PATH}

    - LLVM_URL="http://releases.llvm.org/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
    - echo "Downloading clang+llvm-${LLVM_VERSION} ..."
    - mkdir -p ${DEPS_DIR}/llvm
    - travis_retry wget --no-check-certificate --quiet -O ${DEPS_DIR}/llvm/clang+llvm-${LLVM_VERSION}.tar.xz ${LLVM_URL}
    - pushd `pwd`
    - cd ${DEPS_DIR}/llvm
    - xz -d clang+llvm-${LLVM_VERSION}.tar.xz
    - tar --strip-components=1 -xf clang+llvm-${LLVM_VERSION}.tar
    - popd
    - export PATH=${DEPS_DIR}/llvm/bin:${PATH}

    - CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
    - echo "Downloading CMake ..."
    - mkdir -p ${DEPS_DIR}/cmake
    - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    - cmake --version
    - clang --version
    - ninja --version
    - echo "Build Halide ..."
    - scripts/build-halide.sh
    - echo "Start building..."
    - scripts/build.sh
